[package]
name = "qucom-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ndarray = "0.17.1"
num-complex = "0.4.6"
rand = "0.9.2"
rand_distr = "0.5.1"
wasm-bindgen = "0.2.105"
getrandom = { version = "0.3", features = ["wasm_js"] }
